### ISSUE TITLE
check for duplicates before joining to speed up

### ISSUE THREAD

**Issue by erikarasnick** [geomarker-io/addNarrData#23]
not sure if our current code does this, I will check

**Comment by erikarasnick** [comment]
https://github.com/geomarker-io/addNarrData/blob/2edea8ddc4ca91440884a6becb2c6ca2ed92159a/R/narr_data_functions.R#L76

this is the slowest part

**Comment by cole-brokamp** [comment]
The unexpected long compute time seemed to be happening *before* the files were downloaded using `s3` (a couple of lines above that).  What is the longest compute time happening before that?

**Comment by erikarasnick** [comment]
Nothing before that seems to be lagging for me...

<img width="664" alt="Screen Shot 2021-05-18 at 2 42 17 PM" src="https://user-images.githubusercontent.com/45949235/118706435-5b2df900-b7e7-11eb-8eda-6cfa9e26b300.png">
