### ISSUE TITLE
Issue with using get_narr_data function.

### ISSUE THREAD

**Issue by egecili54** [geomarker-io/addNarrData#6]
I was able to download the data in 3h 18m.
But I am getting the following error. I tried to solve it but failed. Do you have any experience with this error? Thanks

get_narr_data(d, narr_variables = c('air.2m', 'rhum.2m'))

using narr.fst file at C:/Users/GEC9ED/AppData/Local/addNarrData/addNarrData/narr.fst
Error in fst::read_fst(path = narr_fst_filepath, from = narr_row_start,  :
  File header information does not contain the fst format marker. If this is a fst file generated with package version older than v0.8.0, please read (and re-write) your file using fst package versions 0.8.0 to 0.8.10.

**Comment by cole-brokamp** [comment]
Thanks, Emrah.

@erikarasnick -- I originally thought that this could have been an issue with creating the fst file with an older version of the package as the message suggests, but I did so [using version 0.9.0](https://github.com/geomarker-io/narr_raster_to_fst/blob/7b1c766f1ad2cce0c32288301abdeffc29a2066c/renv.lock#L170-L176), so I don't think that's it. It seems like it can find the file, but cannot read it.  Can you try to reproduce this on a Windows machine?

**Comment by cole-brokamp** [comment]
Emrah, can you try to manually download the file and then put it in the place where the package expects it (this could be your working directory) and report what happens then?  After some testing and discussion, we think that the file might have been corrupted on download.

This leads to a bigger issue, which could be that we need to support a better way to download files other than using download.file.  We could use the S3 R package or the aws cli python package to support concurrent multi-threaded downloads.  This could also be useful to check for the most recent version of the data on package load.

**Comment by cole-brokamp** [comment]
This should be fixed now that we rely on the s3 package to download the public files.  This doesn't suffer from the same problems that occur when using "wininet" methods in `download.file` on a windows machine.
